/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/beer1.glb')

  // useFrame(state => {
  //   this.current.rotation.z = state.mouse.y * Math.PI / 2
  // }) 

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload("/models/beer1.glb")
