/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/bot_model.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions.armatureAction.play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.main} />
          <group name="Plane002">
            <skinnedMesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} skeleton={nodes.Plane002_1.skeleton} />
            <skinnedMesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials['Material.003']} skeleton={nodes.Plane002_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bot_model.glb')
