/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Gamepad.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.rotate.play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 2.33, -1.37]} rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.main} />
          <primitive object={nodes.neutral_bone} />
          <group name="gamepad">
            <skinnedMesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['Material.001']} skeleton={nodes.Icosphere.skeleton} />
            <skinnedMesh name="Icosphere_1" geometry={nodes.Icosphere_1.geometry} material={materials['Material.004']} skeleton={nodes.Icosphere_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Gamepad.glb')
